- name: Deploy App
  hosts: app
  tags: deploy-tag # <-- тег для задач с deploy
  become: true

  tasks:
    - name: Install git
      apt:
          name: git
          state: present
          update_cache: yes

    - name: Fetch the latest version of application code
      git:
          repo: 'https://github.com/express42/reddit.git'
          dest: "/home/{{ deploy_user }}/reddit"
          version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
            state: present
            chdir: "/home/{{ deploy_user }}/reddit"

  handlers: # <-- handler на рестар puma.service
      - name: reload puma
        service: name=puma state=restarted
