- name: Configure App
  hosts: app
  tags: app-tag # <-- тег для задач с app
  become: true
  vars:
      db_host: 192.168.10.7
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
          src: templates/db_config.j2
          dest: /home/ubuntu/db_config

    - name: enable puma
      systemd: name=puma enabled=yes
      notify: reload puma

  handlers: # <-- handler на рестар puma.service
      - name: reload puma
        service: name=puma state=restarted
