- name: Configure hosts & deploy application
  hosts: all
  vars:
      mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
  tags: db-tag # <-- Список тэгов для задачи
