name: Run Ansible Lint

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Checkout repo with tests
      uses: actions/checkout@v2
      with:
        repository: "Otus-DevOps-2022-05/hatterfix_infra"
#        ref: 2022-05
        path: "./ansible/playbooks/"


    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@main
      with:
        targets: |
          ./ansible/playbooks
          ./ansible/roles
        args: "-c .ansible-lint"
