name: Run Packer templates validation

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  packer:
#    strategy:
#      matrix:
#        packer-config: ["app.json", "db.json", "immutable.json", "ubuntu16.json"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with tests
        uses: actions/checkout@v2
        with:
          repository: "Otus-DevOps-2022-05/hatterfix_infra"
#         ref: 2022-02
          path: "./packer/"

      - name: Prepare variables files
        uses: canastro/copy-file-action@master
        with:
          source: variables.json.example
          target: variables.json

      - name: Validate template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ubuntu16.json
          arguments: "--var-file=variables.json --syntax-only"
